services:

  # --- LOCAL CLOUD TOOLS --- #
  localstack:
    image: localstack/localstack:2.3
    container_name: qualify-guru-localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack-init.sh:/etc/localstack/init/ready.d/init.sh"
    networks:
      - qualify-guru-network

  # --- QUEUE BROKER --- #
  rabbitmq:
    image: rabbitmq:3-management
    container_name: qualify-guru-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    networks:
      - qualify-guru-network


  # --- LOGS --- #
  loki:
    image: grafana/loki:2.9.2
    container_name: qualify-guru-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - qualify-guru-network

  promtail:
    image: grafana/promtail:2.9.2
    container_name: qualify-guru-promtail
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yml
      - ./logs:/var/log/app_logs
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - qualify-guru-network

  grafana:
    image: grafana/grafana:10.2.2
    container_name: qualify-guru-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    depends_on:
      - loki
    networks:
      - qualify-guru-network

networks:
  qualify-guru-network:
    driver: bridge